---

- name: Create Apache group
  group: name={{ apache_group }} state=present
  tags:
    - apache

- name: Create Apapche log group
  group: name={{ apache_log_group }} state=present
  tags:
    - apache

- name: Create Apache docroot group
  group: name={{ apache_docroot_group }} state=present
  tags:
    - apache

- name: Create Apache user
  user: name={{ apache_user }} groups={{ apache_group }},{{ apache_docroot_group }}  state=present
  tags:
    - apache

- name: Create Apache docroot user
  user: name={{ apache_docroot_user }} groups={{ apache_docroot_group }},{{ apache_log_group }} state=present
  tags:
    - apache

- name: Create Apache base directories
  file: path={{ item }} state=directory owner=root group=root mode=0750
  with_items:
  - "{{ apache_base_directories }}"
  tags:
  - apache

- name: Create Apache docroot directories
  file: path={{ item }} state=directory owner={{ apache_docroot_user }} group={{ apache_docroot_group }} mode=0750
  with_items:
  - "{{ apache_docroot_directories }}"
  tags:
  - apache

- name: Create Apache log directories
  file: path={{ item }} state=directory owner=root group={{ apache_log_group }} mode=2750
  with_items:
  - "{{ apache_log_directories }}"
  tags:
  - apache

- name: Install Apache packages
  yum: name={{ item }} state=installed
  with_items:
   - "{{ packages }}"
  tags:
  - apache

- name: Remove samble page
  file: path={{ sample_page }} state=absent 
  tags:
  - apache
  - remove-sample-page

- name: Remove autoindex module
  lineinfile:
    dest: /etc/httpd/conf.modules.d/00-base.conf
    state: absent
    regexp: '^(.*)mod_autoindex(.*)$'
  tags:
  - apache
  - delete-autoindex-module

- name: Remove include module
  lineinfile:
    dest: /etc/httpd/conf.modules.d/00-base.conf
    state: absent
    regexp: '^(.*)mod_include(.*)$'
  tags:
  - apache
  - delete-include-module

- name: Remove info module
  lineinfile:
    dest: /etc/httpd/conf.modules.d/00-base.conf
    state: absent
    regexp: '^(.*)mod_info(.*)$'
  tags:
  - apache
  - delete-info-module

- name: Remove userdir module
  lineinfile:
    dest: /etc/httpd/conf.modules.d/00-base.conf
    state: absent
    regexp: '^(.*)mod_userdir(.*)$'
  tags:
  - apache
  - delete-userdir-module

- name: Remove dav modules
  file: path=/etc/httpd/conf.modules.d//00-dav.conf state=absent
  tags:
  - apache
  - delete-dav-module

- name: Remove cgi modules
  file: path=/etc/httpd/conf.modules.d//01-cgi.conf state=absent
  tags:
  - apache
  - delete-cgi-module

- name: Remove unnesesary modules files
  file: path={{ item }} state=absent
  with_items:
  - "{{ unnesesary_conf_files }}"
  tags:
  - apache
  - delete-unnesesary-modules-conf-files

- name: Set proper permissions for APACHE_HOME
  file: path=/etc/httpd/conf.d/ mode=640 recurse=yes
  tags: 
  - apache
  - set-permissions
